completed autostart scripts

diff --git a/node-exec b/node-exec
--- a/node-exec
+++ b/node-exec
@@ -1,25 +1,88 @@
-#!/usr/bin/env python
-'''Capture simple video
+#!/bin/sh
+# Automaic run functions for the individual nodes
 
-'''
+savedir=/home/pi
+viddir="$savedir/Videos"
+min_hd_space=$((1024*1024))	# 1 GB
 
-from datetime import datetime
-from pathlib import Path
+echo "INFO: Node powered on"
 
-from picamera import PiCamera
+free_space=`df --output=avail $savedir | tail -n1`
+echo "INFO: Free space: $free_space ($((free_space/1024/1024)) GB)"
 
-import logging
-logging.basicConfig(filename='example.log', encoding='utf-8',format='%(asctime)s - %(levelname)s - %(message)s', level=logging.DEBUG)
+# If space back up nodes
+if [ "$free_space" -lt "$min_hd_space" ]
+then
+    echo "ERROR: not enough space"
+    # TODO: quit
+else 
+    echo "INFO: Saving videos to $viddir"
+fi
 
-logging.info("script started")
-fdir = Path('/home/pi/Videos')
+ifaceup () {
+    # Check if network interface is up
+    file=/sys/class/net/$1/operstate
+    
+    if [ -f "$file" ]; then
+	status=$(cat $file)
+	# status is likely but not definitely "up"
+    else
+	status="down"
+    fi
+    
+    echo "INFO: iface $1: $status"
+    
+    if [ ! "$status" = "down" ]; then
+	return 0
+    else
+	return 1
+    fi
+}
 
-with PiCamera() as picam:
-    dtg = datetime.now()
-    logging.info("recording started")
-    picam.start_recording(f'/home/pi/Videos/{dtg.isoformat()}.h264')
-    picam.wait_recording(5)
-    logging.info("recording stopping")
-    picam.stop_recording()
+test_connection () {
+    ping -q -c 1 -W 1 raspberrypi.local > /dev/null
+    # NOTE: kill SIGINT does not work during ping
+    return $?
+}
 
-logging.info("Script stopping")
+# Make sure usb interface is connected
+ifaceup usb0
+while ! test_connection
+do
+    echo "INFO: waiting for connection"
+    sleep 10
+done
+
+echo "INFO: Array connection established"
+
+# Check time syncing
+ntp_server=$(timedatectl show-timesync | grep "ServerName" | sed 's/.*=//') 
+if [ ! -z $ntp_server ]
+then
+    echo "INFO: Time synced to $ntp_server"
+else
+    # FIXME: does not work
+    echo "WARNING: Time sync server down"
+fi
+
+
+# Stay up if there is an outside connection
+ifaceup wlan0; wlan0_up=$1
+
+if  $wlan0_up 
+then
+    echo "INFO: Outside connection detected: do not quit"
+fi
+
+# Check if user is logged in
+# NOTE: should not matter
+if who | grep -q "pi"
+then
+    echo "INFO: pi is logged in"
+else
+    echo "INFO: pi is not logged in"
+fi
+
+echo "INFO: node-exec completed"
+
+exit 0
